LOAD DATA LOCAL INFILE 'users.txt' INTO TABLE AcutionUser
FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE 'items.txt' INTO TABLE Item
FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE 'categorys.txt' INTO TABLE Category
FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE 'belongsTo.txt' INTO TABLE BelongsTo
FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE 'bids.txt' INTO TABLE BidsInfo
FIELDS TERMINATED BY '|*|';